// Code generated by mockery v2.53.5. DO NOT EDIT.

package git

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockCommandRunner is an autogenerated mock type for the CommandRunner type
type MockCommandRunner struct {
	mock.Mock
}

type MockCommandRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommandRunner) EXPECT() *MockCommandRunner_Expecter {
	return &MockCommandRunner_Expecter{mock: &_m.Mock}
}

// Run provides a mock function with given fields: ctx, name, args
func (_m *MockCommandRunner) Run(ctx context.Context, name string, args ...string) (string, error) {
	_va := make([]interface{}, len(args))
	for _i := range args {
		_va[_i] = args[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, name)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...string) (string, error)); ok {
		return rf(ctx, name, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...string) string); ok {
		r0 = rf(ctx, name, args...)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...string) error); ok {
		r1 = rf(ctx, name, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommandRunner_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockCommandRunner_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - args ...string
func (_e *MockCommandRunner_Expecter) Run(ctx interface{}, name interface{}, args ...interface{}) *MockCommandRunner_Run_Call {
	return &MockCommandRunner_Run_Call{Call: _e.mock.On("Run",
		append([]interface{}{ctx, name}, args...)...)}
}

func (_c *MockCommandRunner_Run_Call) Run(run func(ctx context.Context, name string, args ...string)) *MockCommandRunner_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockCommandRunner_Run_Call) Return(_a0 string, _a1 error) *MockCommandRunner_Run_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommandRunner_Run_Call) RunAndReturn(run func(context.Context, string, ...string) (string, error)) *MockCommandRunner_Run_Call {
	_c.Call.Return(run)
	return _c
}

// RunWithTTY provides a mock function with given fields: ctx, name, args
func (_m *MockCommandRunner) RunWithTTY(ctx context.Context, name string, args ...string) (string, error) {
	_va := make([]interface{}, len(args))
	for _i := range args {
		_va[_i] = args[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, name)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for RunWithTTY")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...string) (string, error)); ok {
		return rf(ctx, name, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...string) string); ok {
		r0 = rf(ctx, name, args...)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...string) error); ok {
		r1 = rf(ctx, name, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommandRunner_RunWithTTY_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunWithTTY'
type MockCommandRunner_RunWithTTY_Call struct {
	*mock.Call
}

// RunWithTTY is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - args ...string
func (_e *MockCommandRunner_Expecter) RunWithTTY(ctx interface{}, name interface{}, args ...interface{}) *MockCommandRunner_RunWithTTY_Call {
	return &MockCommandRunner_RunWithTTY_Call{Call: _e.mock.On("RunWithTTY",
		append([]interface{}{ctx, name}, args...)...)}
}

func (_c *MockCommandRunner_RunWithTTY_Call) Run(run func(ctx context.Context, name string, args ...string)) *MockCommandRunner_RunWithTTY_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockCommandRunner_RunWithTTY_Call) Return(_a0 string, _a1 error) *MockCommandRunner_RunWithTTY_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommandRunner_RunWithTTY_Call) RunAndReturn(run func(context.Context, string, ...string) (string, error)) *MockCommandRunner_RunWithTTY_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCommandRunner creates a new instance of MockCommandRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommandRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommandRunner {
	mock := &MockCommandRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
