// Code generated by mockery v2.53.5. DO NOT EDIT.

package git

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Clone provides a mock function with given fields: ctx, url, branch
func (_m *MockService) Clone(ctx context.Context, url string, branch string) error {
	ret := _m.Called(ctx, url, branch)

	if len(ret) == 0 {
		panic("no return value specified for Clone")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, url, branch)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_Clone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clone'
type MockService_Clone_Call struct {
	*mock.Call
}

// Clone is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - branch string
func (_e *MockService_Expecter) Clone(ctx interface{}, url interface{}, branch interface{}) *MockService_Clone_Call {
	return &MockService_Clone_Call{Call: _e.mock.On("Clone", ctx, url, branch)}
}

func (_c *MockService_Clone_Call) Run(run func(ctx context.Context, url string, branch string)) *MockService_Clone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_Clone_Call) Return(_a0 error) *MockService_Clone_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_Clone_Call) RunAndReturn(run func(context.Context, string, string) error) *MockService_Clone_Call {
	_c.Call.Return(run)
	return _c
}

// GetInfo provides a mock function with given fields: ctx
func (_m *MockService) GetInfo(ctx context.Context) (*CommitInfo, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetInfo")
	}

	var r0 *CommitInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*CommitInfo, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *CommitInfo); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*CommitInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInfo'
type MockService_GetInfo_Call struct {
	*mock.Call
}

// GetInfo is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) GetInfo(ctx interface{}) *MockService_GetInfo_Call {
	return &MockService_GetInfo_Call{Call: _e.mock.On("GetInfo", ctx)}
}

func (_c *MockService_GetInfo_Call) Run(run func(ctx context.Context)) *MockService_GetInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_GetInfo_Call) Return(_a0 *CommitInfo, _a1 error) *MockService_GetInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetInfo_Call) RunAndReturn(run func(context.Context) (*CommitInfo, error)) *MockService_GetInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetRemote provides a mock function with given fields: ctx
func (_m *MockService) GetRemote(ctx context.Context) (string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRemote")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetRemote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRemote'
type MockService_GetRemote_Call struct {
	*mock.Call
}

// GetRemote is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) GetRemote(ctx interface{}) *MockService_GetRemote_Call {
	return &MockService_GetRemote_Call{Call: _e.mock.On("GetRemote", ctx)}
}

func (_c *MockService_GetRemote_Call) Run(run func(ctx context.Context)) *MockService_GetRemote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_GetRemote_Call) Return(_a0 string, _a1 error) *MockService_GetRemote_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetRemote_Call) RunAndReturn(run func(context.Context) (string, error)) *MockService_GetRemote_Call {
	_c.Call.Return(run)
	return _c
}

// GetTopLevel provides a mock function with given fields: ctx
func (_m *MockService) GetTopLevel(ctx context.Context) (string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTopLevel")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetTopLevel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTopLevel'
type MockService_GetTopLevel_Call struct {
	*mock.Call
}

// GetTopLevel is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) GetTopLevel(ctx interface{}) *MockService_GetTopLevel_Call {
	return &MockService_GetTopLevel_Call{Call: _e.mock.On("GetTopLevel", ctx)}
}

func (_c *MockService_GetTopLevel_Call) Run(run func(ctx context.Context)) *MockService_GetTopLevel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_GetTopLevel_Call) Return(_a0 string, _a1 error) *MockService_GetTopLevel_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetTopLevel_Call) RunAndReturn(run func(context.Context) (string, error)) *MockService_GetTopLevel_Call {
	_c.Call.Return(run)
	return _c
}

// Pull provides a mock function with given fields: ctx
func (_m *MockService) Pull(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Pull")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_Pull_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pull'
type MockService_Pull_Call struct {
	*mock.Call
}

// Pull is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) Pull(ctx interface{}) *MockService_Pull_Call {
	return &MockService_Pull_Call{Call: _e.mock.On("Pull", ctx)}
}

func (_c *MockService_Pull_Call) Run(run func(ctx context.Context)) *MockService_Pull_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_Pull_Call) Return(_a0 error) *MockService_Pull_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_Pull_Call) RunAndReturn(run func(context.Context) error) *MockService_Pull_Call {
	_c.Call.Return(run)
	return _c
}

// SetLocalExclude provides a mock function with given fields: patterns
func (_m *MockService) SetLocalExclude(patterns []string) error {
	ret := _m.Called(patterns)

	if len(ret) == 0 {
		panic("no return value specified for SetLocalExclude")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]string) error); ok {
		r0 = rf(patterns)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_SetLocalExclude_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLocalExclude'
type MockService_SetLocalExclude_Call struct {
	*mock.Call
}

// SetLocalExclude is a helper method to define mock.On call
//   - patterns []string
func (_e *MockService_Expecter) SetLocalExclude(patterns interface{}) *MockService_SetLocalExclude_Call {
	return &MockService_SetLocalExclude_Call{Call: _e.mock.On("SetLocalExclude", patterns)}
}

func (_c *MockService_SetLocalExclude_Call) Run(run func(patterns []string)) *MockService_SetLocalExclude_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string))
	})
	return _c
}

func (_c *MockService_SetLocalExclude_Call) Return(_a0 error) *MockService_SetLocalExclude_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_SetLocalExclude_Call) RunAndReturn(run func([]string) error) *MockService_SetLocalExclude_Call {
	_c.Call.Return(run)
	return _c
}

// Sync provides a mock function with given fields: ctx, url, branch, sparseCheckout
func (_m *MockService) Sync(ctx context.Context, url string, branch string, sparseCheckout []string) error {
	ret := _m.Called(ctx, url, branch, sparseCheckout)

	if len(ret) == 0 {
		panic("no return value specified for Sync")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []string) error); ok {
		r0 = rf(ctx, url, branch, sparseCheckout)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_Sync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sync'
type MockService_Sync_Call struct {
	*mock.Call
}

// Sync is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - branch string
//   - sparseCheckout []string
func (_e *MockService_Expecter) Sync(ctx interface{}, url interface{}, branch interface{}, sparseCheckout interface{}) *MockService_Sync_Call {
	return &MockService_Sync_Call{Call: _e.mock.On("Sync", ctx, url, branch, sparseCheckout)}
}

func (_c *MockService_Sync_Call) Run(run func(ctx context.Context, url string, branch string, sparseCheckout []string)) *MockService_Sync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].([]string))
	})
	return _c
}

func (_c *MockService_Sync_Call) Return(_a0 error) *MockService_Sync_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_Sync_Call) RunAndReturn(run func(context.Context, string, string, []string) error) *MockService_Sync_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
