version: "2"

linters:
  enable:
    - errcheck
    # - wrapcheck  # TODO
    - govet
    - ineffassign
    - staticcheck
    - goconst
    # - gocyclo  # TODO
    - misspell
    - whitespace
    - nolintlint
  settings:
    gocyclo:
      min-complexity: 15
  exclusions:
    paths:
      - tmp

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    paths:
      - tmp
