version: 2

before:
  hooks:
    - ./scripts/patch.sh
    - ./scripts/completions.sh

report_sizes: true

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/devbox/
    goarch:
      - amd64
      - arm64
    goos:
      - linux
      - darwin

archives:
  - name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    builds_info:
      group: root
      owner: root
      mtime: "{{ .CommitDate }}"
    files:
      - src: README.md
        info:
          group: root
          owner: root
          mtime: "{{ .CommitDate }}"
      - src: LICENSE
        info:
          group: root
          owner: root
          mtime: "{{ .CommitDate }}"
      - src: completions/*
        info:
          group: root
          owner: root
          mtime: "{{ .CommitDate }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc

release:
  github:
    owner: pilat
    name: devbox

brews:
  - name: devbox
    commit_author:
      name: Vladimir Urushev
      email: vkurushev@gmail.com
    repository:
      owner: pilat
      name: homebrew-devbox
      token: "{{ .Env.CICD_HOMEBREW_GITHUB_TOKEN }}"

    license: MIT
    dependencies:
      - name: git

    extra_install: |
      bash_completion.install "completions/devbox.bash" => "devbox"
      zsh_completion.install "completions/devbox.zsh" => "_devbox"
      fish_completion.install "completions/devbox.fish"
