keeptree: False
with-expecter: True
inpackage: True
resolve-type-alias: False
issue-845-fix: True
dir: "{{.InterfaceDirRelative}}"
outpkg: "{{.PackageName}}"
filename: "mock_{{.InterfaceName}}.go"

packages:
  github.com/pilat/devbox/internal/git:
    interfaces:
      CommandRunner:
      Service:
  github.com/pilat/devbox/internal/pkg/fs:
    interfaces:
      FileSystem:
      FileInfo:
      DirEntry:
