// Code generated by mockery v2.53.5. DO NOT EDIT.

package fs

import (
	os "os"

	mock "github.com/stretchr/testify/mock"
)

// MockFileSystem is an autogenerated mock type for the FileSystem type
type MockFileSystem struct {
	mock.Mock
}

type MockFileSystem_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileSystem) EXPECT() *MockFileSystem_Expecter {
	return &MockFileSystem_Expecter{mock: &_m.Mock}
}

// Getwd provides a mock function with no fields
func (_m *MockFileSystem) Getwd() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Getwd")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFileSystem_Getwd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Getwd'
type MockFileSystem_Getwd_Call struct {
	*mock.Call
}

// Getwd is a helper method to define mock.On call
func (_e *MockFileSystem_Expecter) Getwd() *MockFileSystem_Getwd_Call {
	return &MockFileSystem_Getwd_Call{Call: _e.mock.On("Getwd")}
}

func (_c *MockFileSystem_Getwd_Call) Run(run func()) *MockFileSystem_Getwd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFileSystem_Getwd_Call) Return(_a0 string, _a1 error) *MockFileSystem_Getwd_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFileSystem_Getwd_Call) RunAndReturn(run func() (string, error)) *MockFileSystem_Getwd_Call {
	_c.Call.Return(run)
	return _c
}

// ReadDir provides a mock function with given fields: path
func (_m *MockFileSystem) ReadDir(path string) ([]DirEntry, error) {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for ReadDir")
	}

	var r0 []DirEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]DirEntry, error)); ok {
		return rf(path)
	}
	if rf, ok := ret.Get(0).(func(string) []DirEntry); ok {
		r0 = rf(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]DirEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFileSystem_ReadDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadDir'
type MockFileSystem_ReadDir_Call struct {
	*mock.Call
}

// ReadDir is a helper method to define mock.On call
//   - path string
func (_e *MockFileSystem_Expecter) ReadDir(path interface{}) *MockFileSystem_ReadDir_Call {
	return &MockFileSystem_ReadDir_Call{Call: _e.mock.On("ReadDir", path)}
}

func (_c *MockFileSystem_ReadDir_Call) Run(run func(path string)) *MockFileSystem_ReadDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockFileSystem_ReadDir_Call) Return(_a0 []DirEntry, _a1 error) *MockFileSystem_ReadDir_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFileSystem_ReadDir_Call) RunAndReturn(run func(string) ([]DirEntry, error)) *MockFileSystem_ReadDir_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveAll provides a mock function with given fields: path
func (_m *MockFileSystem) RemoveAll(path string) error {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for RemoveAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFileSystem_RemoveAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveAll'
type MockFileSystem_RemoveAll_Call struct {
	*mock.Call
}

// RemoveAll is a helper method to define mock.On call
//   - path string
func (_e *MockFileSystem_Expecter) RemoveAll(path interface{}) *MockFileSystem_RemoveAll_Call {
	return &MockFileSystem_RemoveAll_Call{Call: _e.mock.On("RemoveAll", path)}
}

func (_c *MockFileSystem_RemoveAll_Call) Run(run func(path string)) *MockFileSystem_RemoveAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockFileSystem_RemoveAll_Call) Return(_a0 error) *MockFileSystem_RemoveAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFileSystem_RemoveAll_Call) RunAndReturn(run func(string) error) *MockFileSystem_RemoveAll_Call {
	_c.Call.Return(run)
	return _c
}

// Stat provides a mock function with given fields: path
func (_m *MockFileSystem) Stat(path string) (FileInfo, error) {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 FileInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (FileInfo, error)); ok {
		return rf(path)
	}
	if rf, ok := ret.Get(0).(func(string) FileInfo); ok {
		r0 = rf(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(FileInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFileSystem_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type MockFileSystem_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
//   - path string
func (_e *MockFileSystem_Expecter) Stat(path interface{}) *MockFileSystem_Stat_Call {
	return &MockFileSystem_Stat_Call{Call: _e.mock.On("Stat", path)}
}

func (_c *MockFileSystem_Stat_Call) Run(run func(path string)) *MockFileSystem_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockFileSystem_Stat_Call) Return(_a0 FileInfo, _a1 error) *MockFileSystem_Stat_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFileSystem_Stat_Call) RunAndReturn(run func(string) (FileInfo, error)) *MockFileSystem_Stat_Call {
	_c.Call.Return(run)
	return _c
}

// WriteFile provides a mock function with given fields: path, data, perm
func (_m *MockFileSystem) WriteFile(path string, data []byte, perm os.FileMode) error {
	ret := _m.Called(path, data, perm)

	if len(ret) == 0 {
		panic("no return value specified for WriteFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []byte, os.FileMode) error); ok {
		r0 = rf(path, data, perm)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFileSystem_WriteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteFile'
type MockFileSystem_WriteFile_Call struct {
	*mock.Call
}

// WriteFile is a helper method to define mock.On call
//   - path string
//   - data []byte
//   - perm os.FileMode
func (_e *MockFileSystem_Expecter) WriteFile(path interface{}, data interface{}, perm interface{}) *MockFileSystem_WriteFile_Call {
	return &MockFileSystem_WriteFile_Call{Call: _e.mock.On("WriteFile", path, data, perm)}
}

func (_c *MockFileSystem_WriteFile_Call) Run(run func(path string, data []byte, perm os.FileMode)) *MockFileSystem_WriteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]byte), args[2].(os.FileMode))
	})
	return _c
}

func (_c *MockFileSystem_WriteFile_Call) Return(_a0 error) *MockFileSystem_WriteFile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFileSystem_WriteFile_Call) RunAndReturn(run func(string, []byte, os.FileMode) error) *MockFileSystem_WriteFile_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFileSystem creates a new instance of MockFileSystem. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileSystem(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileSystem {
	mock := &MockFileSystem{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
